---
- hosts: jenkins
  remote_user: "{{ remote_user }}"
  sudo: True
  tasks:
    - name: Set hostname
      hostname: name={{ hostname }}
      tags:
        - newrelic

    - name: Install common Ops packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=600
      with_items:
        - htop
        - python-virtualenv
        - python-pip
        - sharutils
        - s3cmd
        - python-magic  # Make s3cmd happier
        - mosh
        - tmux
        - mc
        - python-dev
        - libffi-dev
        - libssl-dev
        - subversion

    - name: Install a newer kernel
      apt: name=linux-image-{{ kernel }} state=present update_cache=yes cache_valid_time=600
      with_items:
        - "{{ kernel }}"
        - "linux-image-extra-{{ kernel }}"
      register: kernel_installed

    - name: Reboot server
      shell: reboot
      when: "kernel_installed|changed"

    - name: Wait for server to restart
      local_action:
        module: wait_for host={{ inventory_hostname }} port=22 delay=1
      sudo: false
      when: "kernel_installed|changed"

    - name: Add NewRelic repository key
      apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
      tags:
        - newrelic

    - name: Add NewRelic repository
      apt_repository:
        repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
        state=present
        update_cache=yes
      tags:
        - newrelic

    - name: Install NewRelic
      apt: name=newrelic-sysmond state=present update_cache=yes cache_valid_time=300
      tags:
        - newrelic

    - name: Copy NewRelic Configuration
      template:
        src: templates/nrsysmond.cfg.j2
        dest: /etc/newrelic/nrsysmond.cfg
        group: newrelic
        owner: root
        mode: 0640
      notify:
        - Restart newrelic
      tags:
        - newrelic

    - name: Install mailutils for email sending
      apt: name=mailutils state=present update_cache=yes cache_valid_time=600

    - name: Set Postfix to listen on 127.0.0.1 only
      command:
        postconf -e 'inet_interfaces = 127.0.0.1'
      notify:
        - Restart Postfix

    - name: Install nginx
      apt: name=nginx-light state=present update_cache=yes cache_valid_time=600

    # We are going into maintenance mode, stop nginx.
    - name: Stop nginx
      service: name=nginx state=stopped
      tags:
        - install-plugins

    - name: Copy SSL key
      copy:
        src=ssl/ssl.key
        dest=/etc/nginx/ssl.key
        force=yes
        mode=0600
        owner=root
        group=root

    - name: Copy SSL cert
      copy:
        src=ssl/ssl.crt
        dest=/etc/nginx/ssl.crt
        force=yes
        mode=0600
        owner=root
        group=root

    - name: Copy nginx configuration
      template:
        src: templates/nginx-cfg.j2
        dest: /etc/nginx/sites-enabled/default
        group: root
        owner: root
        mode: 0644
      notify: Reload Nginx

    - name: Add Docker Repository Key
      apt_key:
        state=present
        keyserver=keyserver.ubuntu.com
        id=36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: Add Docker Repository
      apt_repository:
        repo='deb https://get.docker.io/ubuntu docker main'
        state=present
        update_cache=yes

    # Version 1.6 changed image format and doesn't work with Deis
    # See https://github.com/deis/deis/issues/3550
    - name: Install Docker 1.5
      apt: name=lxc-docker-1.5.0 state=present update_cache=yes cache_valid_time=600

    - name: Set Docker to use AUFS
      lineinfile:
        dest=/etc/default/docker
        regexp=^DOCKER_OPTS=
        line='DOCKER_OPTS="-s aufs"'
      notify: Restart Docker

    - name: Add Jenkins-CI Repository Key
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

    - name: Add Jenkins-CI Repository
      apt_repository:
        repo='deb http://pkg.jenkins-ci.org/debian binary/'
        state=present
        update_cache=yes

    - name: Install Jenkins-CI
      apt: name=jenkins state=present update_cache=yes cache_valid_time=600
      notify:
        - Restart Jenkins
      register: install_jenkins

    - name: Add Jenkins user to docker group
      user: name=jenkins groups=docker
      notify: Restart Jenkins

    - name: Set Jenkins-CI to listen only on 127.0.0.1
      lineinfile:
        dest=/etc/default/jenkins
        regexp=^JENKINS_ARGS=
        line='JENKINS_ARGS="--webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
      notify: Restart Jenkins

    - name: Set Jenkins-CI gitconfig
      template:
        src: templates/gitconfig.j2
        dest: /var/lib/jenkins/.gitconfig
        group: jenkins
        owner: jenkins
        mode: 0640
        backup: yes
      tags:
        - jenkins-conf

    - name: Start nginx
      service: name=nginx state=started
      tags:
        - install-plugins

    - name: Copy 'remove-docker-image' script
      copy:
        src: bin/remove-docker-images.sh
        dest: /usr/local/bin/remove-docker-images.sh
        mode: 0755

    - name: Create cron job for 'remove-docker-images'
      cron: name="Remove docker images" minute=0 hour=3 weekday=0
            user="root" job="/usr/local/bin/remove-docker-images.sh 2> /dev/null"
            cron_file=remove_docker_images

    - name: Copy s3cfg configuration (used for backups)
      template:
        src=templates/s3cfg.j2
        dest="/home/{{ remote_user }}/.s3cfg"
        mode=0600

    - name: Create jenkins backup job
      cron: name="Backup Jenkins" minute=0 hour=4
            user="root" job="s3cmd -c /home/{{ remote_user }}/.s3cfg put -r /var/lib/jenkins/backups/*.zip s3://{{ aws_backup_bucket }} --encrypt 2> /dev/null"
            cron_file=backup_jenkins

    - name: Copy docker-squash
      unarchive:
        src=docker-squash/docker-squash-linux-amd64-v0.1.0.tar.gz
        dest=/usr/local/bin/

    - name: Allow docker-squash for user jenkins
      lineinfile: 'dest=/etc/sudoers line="jenkins  ALL = NOPASSWD:  /usr/local/bin/docker-squash"'

    # Add Maxmind repo and packages
    # https://github.com/maxmind/geoipupdate
    - name: Add MaxMind repository
      apt_repository: repo='ppa:maxmind/ppa'

    - name: Download MaxMind geoipupdate
      apt: name='geoipupdate' update_cache=yes

  handlers:
    - name: Reload Nginx
      service: name=nginx state=reloaded
      sudo_user: root

    - name: Restart Jenkins
      service: name=jenkins state=restarted
      sudo_user: root

    - name: Restart Postfix
      service: name=postfix state=restarted
      sudo_user: root

    - name: Restart newrelic
      service: name=newrelic-sysmond state=restarted
      sudo_user: root

    - name: Restart Docker
      service: name=docker state=restarted
      sudo_user: root

  vars_files:
    - local_variables.yml
